# Generated by Django 4.2.13 on 2024-07-07 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeslot",
            old_name="end_time",
            new_name="time",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="start_time",
        ),
    ]
