# Generated by Django 4.2.13 on 2024-07-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_rename_end_time_timeslot_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeslot",
            name="date",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="time",
        ),
        migrations.AddField(
            model_name="timeslot",
            name="datetime",
            field=models.DateTimeField(default=None),
        ),
    ]
