# Generated by Django 4.2.13 on 2024-07-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_remove_timeslot_date_remove_timeslot_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeslot",
            name="datetime",
        ),
        migrations.AddField(
            model_name="timeslot",
            name="date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="time",
            field=models.TimeField(default=None),
        ),
    ]
