# Generated by Django 4.2.13 on 2024-07-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_cuisine_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuisine",
            name="image",
            field=models.ImageField(upload_to="cuisines/"),
        ),
    ]
