# Generated by Django 4.2.13 on 2024-07-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_alter_cuisine_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuisine",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=None),
        ),
    ]
