# Generated by Django 4.2.13 on 2024-07-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_alter_cuisine_price_alter_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant.timeslot",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
